#!/usr/bin/env ruby

#puts "Hello World!"

#system("ls")

myCase = ARGV[0]
#puts "#{ARGV[0]}"


case myCase
	when "create"
	system "git clone #{ARGV[1]}"
	z= `ls -td -- */ | head -n 1 | cut -d'/' -f1`
	z=z.chomp
	#puts z.length
	#puts "cd #{z}"
	Dir.chdir "#{z}"
	puts z
	#system "cd #{z}"
	system "cd .."
	system "ls"
	#system "cd #{ARGV[1]}"
	system "git init"
	system "git pull"
	puts "Creating branch #{ARGV[2]}"
#	system "cd #{ARGV[1]}"
	system "git branch #{ARGV[2]}"
	system "git checkout #{ARGV[2]}"
	

	
end
